# Generated by Django 4.2.3 on 2026-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='user',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='course',
        ),
    ]
